FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash points

RUN mkdir /etc/points

RUN mkdir /var/lib/points

RUN chown points:points /etc/points /var/lib/points

WORKDIR /home/points

COPY --chown=points:points linux64/* ./run.sh /home/points/

USER points

CMD ["/home/points/run.sh"]
