FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash points

RUN mkdir /etc/points

RUN mkdir /var/lib/points

RUN chown points:points /etc/points /var/lib/points

WORKDIR /home/points

COPY --chown=points:points linux64/* /home/points/

COPY --chown=points:points run.sh /home/points/

USER points

CMD ["/home/points/run.sh"]
